### ISSUE TITLE
Weight distribution

### ISSUE THREAD

**Issue by LisaHuang2017** [YADAMSS/Matemasie-Font#10]
[Proofs-matemasie2023.12.11_Lisa_notes.pdf](https://github.com/YADAMSS/Matemasie-Font/files/13718634/Proofs-matemasie2023.12.11_Lisa_notes.pdf)

The difference in the weight between the top and bottom could be managed with more consistency. Especially the transition between the heavy weight on the top to the lighter weight on the bottom, which seems too sudden on some letters but is more gradual on most others.
Glyphs that could be improved: 
- [x] S and s (more weight in the middle for smoother transition);
- [x] z (same as S);
- [x] 2, 3, 5 (slightly more weight in the middle);
- [x] 4 (less weight in the middle, it is too heavy for almost the entire glyph);

- [x] Then, it is either the bottom of c, e, g, t, s, x, 2, 3, and 5 that is too thin;
- [x] Or, the thinnest part of letters b, d, g,... that is a bit too thick. Both keep that inconsistent contrast that confuses a bit the reading texture.

**Comment by YADAMSS** [comment]
Thanks Lisa for your comments, I will start working as soon as I can. I am currently traveling, back to my country.

**Comment by YADAMSS** [comment]
Hi @LisaHuang2017, could you please check if the issue was resolved as you suggested?
