### ISSUE TITLE
Rename "source" folder to "sources"

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#13]
In order to get the automated builds working through GitHub Actions, the folder "source" needs to be renamed "sources".

This is best done using the Terminal app.

Steps:
1. In Glyphs, save any changes to the font, then close Glyphs.
2. In GitHub Desktop, commit any changes and push them to the server (as in standard workflow).
3. In GitHub Desktop, in the Repository menu, choose "Open in Terminal" to open the Terminal app.
4. In the Terminal app, type the following command, then hit Enter or Return:
```
git mv 'source ' sources
```
5. Close the Terminal app, return to GitHub Desktop. You should see in the "Changes" sidebar that "source" has become "sources". The Changes list will show blue arrows for each of the files in the source/sources folder, indicating that git has noticed the rename and knows the new locations for the existing files. In Finder, if you open the repo's folder, then open the "sources" folder, you should see everything that was in the "source" folder there, exactly as it was before.
6. If all of the status-checks listed in step 5 are true, then you can commit the changes in GitHub Desktop and push them to the server.
7. When you next edit the font, you will need to open the .glyphs file from Finder, because the Glyphs app does not (yet) know that the old folder name has been changed.

**Comment by n8willis** [comment]
(side note: it is best to copy the command in step 4 using the copy-button on the right side of the line, then paste that command into Terminal.)

**Comment by YADAMSS** [comment]
Hi, Done!
