### ISSUE TITLE
Move font source files to "sources" folder

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#14]
After completing #13, the .glyphs source files need to be moved from `sources/Source-Glyphs` up one level, so that they are in `sources`. This is also a requirement to get the automated builds running via GitHub Actions.

The files can be moved using Finder, but it would be better (if possible) to move them using Terminal, so that git tracks the change in location.

Steps:
1. In Glyphs, save any changes to the font, then close Glyphs.
2. In GitHub Desktop, commit any changes and push them to the server (as in standard workflow).
3. In GitHub Desktop, in the Repository menu, choose "Open in Terminal" to open the Terminal app.
4. In the Terminal app, type the following command, then hit Enter or Return:
```
git mv sources/Source-Glyphs/Matemasie.glyphs sources/Matemasie.glyphs
```
5. In the Terminal app, type the following command, then hit Enter or Return:
```
git mv sources/Source-Glyphs/MATEMASIE.glyphs sources/MATEMASIE.glyphs
```
6. In the Terminal app, type the following command, then hit Enter or Return:
```
git mv sources/Source-Glyphs/MATEMASIE-Regular.ttf MATEMASIE-Regular.ttf
```
7. In the Terminal app, type the following command, then hit Enter or Return:
```
git rm sources/Source-Glyphs
```
8. Close the Terminal app, return to GitHub Desktop. You should see in the "Changes" sidebar blue arrows for each of the files that were moved, indicating that git has noticed the rename and knows the new locations for the existing files. The Changes sidebar should also include a red marker indicating that the "Source-Glyphs" folder (which is now empty, after the files were moved) has been deleted. In Finder, if you open the repo's folder, you should find all of the files in their new locations.
9. If all of the status-checks listed in step 8 are true, then you can commit the changes in GitHub Desktop and push them to the server.
10. When you next edit the font, you will need to open the .glyphs file from Finder, because the Glyphs app does not (yet) know that the old folder name has been changed.

Note: eventually, the .ttf files (and any .otf files) will be removed from the repo, because the builder will automatically make new ones using GitHub Actions. For now, moving them out of the `sources` folder is all that is required.

**Comment by YADAMSS** [comment]
Done and everything is working fine!
