### ISSUE TITLE
Balance of "z" (and, to a smaller extent, "s")

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#15]
I think that the bottom/baseline stroke of "z" needs to be longer, extending further to the right. In general, it's a letterform that should have symmetrical width — for instance, if you drew a line that connected the top to the bottom on each side, one would expect roughly the same angles of those lines to be seen.

Rough sketch here, to hopefully show what I mean:
<img width="1146" alt="sxz-side-angles" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/0f9bbbc5-d9eb-4763-9b89-5728711b5106">

You can also use the ruler tool in Glyphs (while in drawing mode) to make lines and see the angles they're at.

- The "x" is the same angle on both sides.
- The "s" is slightly different; the angle on the right side is about 1 degree more, depending on how you measure.
- The "z" is 9.6 degrees on the left side and 16 degrees on the right side.

This angle-measuring is just a mathematical way to show the difference; when someone uses the font, the result of the big differences in angles is that "z" looks a little bit like it's skewing leftward. It also leaves more empty space underneath the right side, which will make it more difficult to space well.

I also think that "s" shows a similar skews-to-left / extra-space-on-bottom-right issue, even though the angle measurement isn't as far apart. That's likely because the sides of "s" reach their widest points much lower on the left than it does on the right. But it's kind of the same optical effect, where the bottom of the letter appears a bit too light on the right or a bit off-center skewing to the left.

Small adjustments; I hope the description of them makes it easier to look for. I would suggest testing some "z"s mixed in with several lines of "oooooo" in paragraph form, then the same with "s".

**Comment by YADAMSS** [comment]
> I think that the bottom/baseline stroke of "z" needs to be longer, extending further to the right. In general, it's a letterform that should have symmetrical width — for instance, if you drew a line that connected the top to the bottom on each side, one would expect roughly the same angles of those lines to be seen.
> 
> Rough sketch here, to hopefully show what I mean: <img alt="sxz-side-angles" width="1146" src="https://private-user-images.githubusercontent.com/2192132/294000027-0f9bbbc5-d9eb-4763-9b89-5728711b5106.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NzYwMDEsIm5iZiI6MTcwNDY3NTcwMSwicGF0aCI6Ii8yMTkyMTMyLzI5NDAwMDAyNy0wZjliYmJjNS1kOWViLTQ3NjMtOWI4OS01NzI4NzExYjUxMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDEwMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBhYWU1MjVhMDRmOTYwY2RiMzE2NGQ3ZTM0ZTJmMzk4YzcyMTJkNzUzZGVkYTllNzZiMTZiZmE3MzJmZjRmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vzd-Y6sERXtq9Vxw9ta_Ry4GkOJ2znQSWk3AsHEEtXc">
> 
> You can also use the ruler tool in Glyphs (while in drawing mode) to make lines and see the angles they're at.
> 
> * The "x" is the same angle on both sides.
> * The "s" is slightly different; the angle on the right side is about 1 degree more, depending on how you measure.
> * The "z" is 9.6 degrees on the left side and 16 degrees on the right side.
> 
> This angle-measuring is just a mathematical way to show the difference; when someone uses the font, the result of the big differences in angles is that "z" looks a little bit like it's skewing leftward. It also leaves more empty space underneath the right side, which will make it more difficult to space well.
> 
> I also think that "s" shows a similar skews-to-left / extra-space-on-bottom-right issue, even though the angle measurement isn't as far apart. That's likely because the sides of "s" reach their widest points much lower on the left than it does on the right. But it's kind of the same optical effect, where the bottom of the letter appears a bit too light on the right or a bit off-center skewing to the left.
> 
> Small adjustments; I hope the description of them makes it easier to look for. I would suggest testing some "z"s mixed in with several lines of "oooooo" in paragraph form, then the same with "s".

Hi Nate, I am not sure I understood your recommendations ABOUT SXZ. , please look at the images below If that is what you asked
<img width="445" alt="Screenshot 2024-01-08 at 03 44 34" src="https://github.com/YADAMSS/Matemasie-Font/assets/47873757/e756bf78-73e6-4225-8cdc-19a86a421a3e">
<img width="752" alt="Screenshot 2024-01-08 at 03 50 41" src="https://github.com/YADAMSS/Matemasie-Font/assets/47873757/b740081c-2edc-4bcc-a20f-08626e0be171">


 also want to notice according to the Matemassie principle, the upper shapes are wider and thicker than the lower ones

**Comment by n8willis** [comment]
Hi Adam,

Not exactly. It's not about the top being equally as wide as the bottom, it's about left-to-right symmetry on the bottom. Let me see if I can make a new illustration that better clarifies.

**Comment by n8willis** [comment]
Let me try this. Look for the sizes of areas enclosed in the blue triangles.

<img width="342" alt="matemasie-x" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/2e276083-3af5-402b-b859-7ed76aa19259">

The "x" is perfectly symmetrical in the horizontal: the left and right triangles are the equal in size. This is what you want.

<img width="282" alt="matemasie-z" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/0792b1dc-513f-433f-83b7-7efd78381b36">

The "z" is very asymmetrical: the right triangle is much larger than the left one.

<img width="274" alt="matemasie-s" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/bfe3e0d2-a675-40cd-af06-2bfc89a01420">

The "s" is somewhat asymmetrical: the right triangle is somewhat larger than the left one.

The triangles here are showing the amount of open space that is "beneath" the widest part of each letter. It is not measuring space inside the letter (in the counters), just what is there if you held a ruler or straight-edge up to it. When there is more open space beneath one side than beneath the other side, the result is that the letter is optically off-center.

Not every glyph is required to be symmetrical; some of them ("r" for example) are completely different on the left & right half, deliberately. But "s" and "z" should have symmetrical triangles if you measure them this way..

**Comment by YADAMSS** [comment]
Thanks Nate, I understand now, I'll work on it.
Thanks a lot
