### ISSUE TITLE
The ".gitignore" file should be updated

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#2]
There is an issue with the `.gitignore` file in the top level of the repository.

The contents of the `.gitignore` file in the repository should match what is shown in the project-template repository's .gitignore file, seen here: https://github.com/googlefonts/googlefonts-project-template/blob/main/.gitignore

Because it does not currently match, several automatically-used files (such as, most importantly, the .DS_Store files in each folder) that belong to the MacOS operating system are being tracked by Github Desktop every time those files are refreshed by a computer. That makes it hard to synchronize the repository, because the .DS_Store files are refreshed by MacOS on the local computer and they conflict with the duplicate files stored in the GitHub repository.

It is 100% safe to exclude them by updating the `.gitignote` file contents, because they do not affect the font project at all.

**Comment by YADAMSS** [comment]
Can you verify, I updated it!

**Comment by n8willis** [comment]
Perfect!
