### ISSUE TITLE
Feedback 2023-11-20 NW

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#3]
This is feedback on the version of the font shown in the 2023-11-20 PDF and the attached images are me marking up some things seen on page 2 and 4.

All in all, things are looking really good! I think the capitals are looking really nice; I especially like the solutions to K, V, and W, which are not simple to make cohesive. I also really like the : ; and @ .

I have highlighted a couple of letterforms that I think could use further refinement, first based on potentials for confusability. 
- Capital L: many traditional designs of L have a flared "vertical serif" on the right side of L. I think that would help here, both to increase the distinctiveness from capital I and to to allow some more internal curvature. I also think that the bottom-left corner of the L could be pulled straighter into more of an angle (without becoming totally angular, that is -- somewhat like the bottom-left corner of D, which works very well), and differentiate it more from capital I and lowercase l and t.
- Capital Q has a different curvature at the top than does capital O; I think it would be improved to have them match more closely. It may also be that the "tail" on Q is too small and could get lost. Have you tried making a tail that sits entirely below the baseline? There is more room below the baseline.
- Capital Z and lowercase z still read, to me, much too similar to the numeral 2. I think it would be possible to make them more distinct by trying a Z/z construction that is horizontally flat, or even curves downward slightly, on the top. You would still be able to reinforce the roundedness of it on the corners. I think the diagonal stroke in Z/z also should be straighter and less curvy. In the big-picture view, a 2 must have upward-curvature at the top and often (almost always) has curves in its diagonal stroke; making the Z/z less curved in those places (and making the 2 more curved in those places) helps them remain distinct.
- The counter inside capital P and capital R should ideally be more similar in shape to each other.

In the lowercase, I think that the f and t need a little refinement.
- the lowercase f looks too much like a capital F -- because there is a lot of weight on the top and the top is quite flat. One thing you could do is make the stem of the f more upright, like in i and j, and have the "hook" on the top leaning over more. I also think it would help to have the crossbar of f join to the stem more angularly  -- using much the same join as the crossbar on lowercase t. That change would also make the top half of f less dark.
- On lowercase t, I think the main vertical stem it too wide, and on the outside (left side), the width makes it very round especially at the bottom; together those factors make it very close to L. A thinner stem would help. Also I think that the "tail" (or out-stroke) looks a little bit flat; it can curve upwards more, like the bottom of c or e; doing more curvature there would also allow the stem of t to stay straighter.
- Ideally, you would want the crossbars of t and f to be at the same height. I think that the t crossbar is closer to being at the ideal height; it could also go a little bit lower. If it moves lower, and the f is adjusted in some of the ways I suggested above, then the f crossbar could be moved upwards -- without having it collide with the top of f.

Some other stray observations:
- I like the construction of the middle of w, but I think it is slightly too wide. It works great in capital W; lowercase w just needs to narrow a bit. It could also have more weight at the "peaks" (basically, both suggestions are to refine it to be more like capital W).
- The aperture inside lowercase e looks to be too far to the left. An e has a different stroke construction from b or g or p; for those I think the alignment of the aperture is correct, because they are a stem + a round bowl. But e is drawn using the same stroke motion as c or o, so the aperture should appear similarly "centered". This is not a major shift-to-the-right at all, but a small one.
- Lowercase s (and z) look a little too thin/light on the bottom. (If you squint at a row of o or n letters, versus an s or a z, the s or z is much lighter. This is what I highlighted on the page 4 image.) I think some more thickness could be added to the bottom curve of s, either on the inside or the outside. 
- With z I don't have a recommendation yet, because I think the confusability-with-2 questions should be solved first. Really, z and capital Z should just be similar; no special differences between Z and z to worry about.
- The tail on lowercase y is not as long (proportionally) as it is on capital Y.

There are also a few "page texture" or "multiple letter" observations to share based on looking at full-page samples:

The light/dark ratios are not the same across the letters. Obviously they would not ever be mathematically exact, but you can make them more similar and it will be helpful in full texts. Once you have the skeleton/construction where it needs to be, you can further refine the light/dark proportions separately. 
- For example: some of the lowercase "straight + round" letters (a, b, d, g, p, q) look much darker on the page than o, mostly because they are wider than o. You could perhaps resolve this by narrowing those letters a bit, bringing the bowls inward or making the vertical straight stem thinner. This is something I would recommend getting feedback from other type designers about; they may have good practical suggestions.
- I think it is also noticeable that the counter inside of closed lowercase letters is quite a bit smaller, proportionally, than the counter inside the closed capital letters. Looking at it in a full page, I think that solution is probably to increase the size of the lowercase counters somewhat. The reason is that there are letters like c that already have larger spaces inside them, and the spaces inside the straight-sided letters (h and n, for example) are also larger than the size of the counter in o. 

The numerals are looking much improved from before. I really like the distinct straighter-outside-shape; it works super well for making zero distinct from O and o. I also like the one a lot.
- I think you could push the middle-angle of three further inward (maybe borrowing some technique from M, W, or w?).
- I think the top-left corner of six is still slightly too square; that is normally a pure-round curve on top -- the top-left curve of 9 is correct, and would work well on six.
- Conversely, I think that the top-left corner of seven should be more square; the top of seven, like Z or z, is usually flat, so you can make it look "flatter" without changing everything by just adjusting the corners.
- Also on seven, I think the leg is touching the baseline too far left; it almost looks like it would be unbalanced. It's usually best to have the leg somewhere clearly underneath the top, as if it was giving support.
- Finally, I think that the top-right corner of five should be more square. The top of five, like seven, is traditionally straight; in this proof, the five and the six are a little too similar and could be confused. A more angular top-right corner of five would solve that somewhat, as would making the six rounder (in the bullet-point above).

I think that is all that I have suggestions for for now. Good that you have been adding diacritics and symbols; I look forward to seeing more!

![Proofs-matemasie2023 11 20-NW-feedback-p02](https://github.com/YADAMSS/Matemasie-Font/assets/2192132/5d14a81f-bb26-4160-bf33-272db1fc5bd2)

![Proofs-matemasie2023 11 20-NW-feedback-p04](https://github.com/YADAMSS/Matemasie-Font/assets/2192132/af928890-59ac-4d72-aca4-83006b1c6275)

**Comment by n8willis** [comment]
Whoops; one other thing I had marked but forgot to say anything about: I think the counter inside of nine should be adjusted to be the same shape (slightly square) as seen in the six and eight....

**Comment by YADAMSS** [comment]
Thanks Nate for the feedback and comments, I will review them carefully and make necessary improvements.
