### ISSUE TITLE
Numerals should be tabular / equal width by default

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#30]
It's important (and I think it's required) that the numerals 0 to 9 be "tabular", meaning that the total widths of each number plus its sidebearings adds up to the same, for every number. That keeps numbers aligned vertically when they are in columns.

Looking at the numbers in the latest file, "4" is the widest. So the plan is to choose the correct sidebearings for "4", then see what the total width of 4-and-sidebearings is, then use that total as the total for every other number.

Most of the numerals look like they should work in this tabular condition, but it is possible that when you do it, you might think (for example) "1" is too far apart compared to everything else, and alter the design of "1" somewhat to make it wider.

(screenshot showing rows of the same number per line; you want all of these lines to be the same length)
<img width="335" alt="Screen Shot 2024-05-08 at 2 29 55 PM" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/1bba4e82-7e91-4510-a387-5a1bbb7858ca">

**Comment by davelab6** [comment]
Proportional numerals is my policy for gf :) it's good to have a tnum feature though

**Comment by tphinney** [comment]
Even back in the day at Adobe, which was pretty aggressively pro-tabular and they expected it for most fonts, it was not necessary when the typeface in question is one that was very unlikely to be used in tabular settings.

That is, will it be used for body text in situations where the numbers actually benefit from lining up from one line to the next? I figure, if it is too much of a display face to likely be used for, say, the listings and prices on a menu, then there was definitely no reason to make the default numerals tabular.

And seeing as Google’s policy leans the opposite direction, then def does not make sense for Matemasie

**Comment by YADAMSS** [comment]
Hi all, thank you for your comments.

Regarding Matemasie, I also think it's probably a good idea to ensure that the numerals 0 to 9 are "tabular". Additionally, I think it would be beneficial to have common elements such as dates, times, addresses, and telephone numbers well-aligned to ensure readability. If this doesn't conflict with the overall project or Google’s policy, I would like to work on making the numerals 0 to 9 "tabular".

**Comment by n8willis** [comment]
Those are definitely good checks to do. Although, since it's evidently not required, I would suggest giving yourself a time-limit on it. If you find some things needing adjustment, that's good.

But if it seems like it'd be taking more than a little time to rework the numerals, consider pausing it, because it shouldn't be the highest thing on the priority list. After all, you can always add a tabular set later on.

**Comment by YADAMSS** [comment]
@tphinney ,hello Thomas ,Well noted. Thanks for the details.

**Comment by YADAMSS** [comment]
> Those are definitely good checks to do. Although, since it's evidently not required, I would suggest giving yourself a time-limit on it. If you find some things needing adjustment, that's good.
> 
> But if it seems like it'd be taking more than a little time to rework the numerals, consider pausing it, because it shouldn't be the highest thing on the priority list. After all, you can always add a tabular set later on.

I GOT IT!
