### ISSUE TITLE
Feedback 2023-12-01 LH

### ISSUE THREAD

**Issue by LisaHuang2017** [YADAMSS/Matemasie-Font#5]
This is the feedback based on the Matemasie Glyphs file as of Dec. 01, 2023. 

Following the feedback from @n8willis on November 20th (https://github.com/YADAMSS/Matemasie-Font/issues/3): 
I agree with Nathan about all his points, especially about the capital letter L. Its ending could look more like that of C, E, or K.
The lowercase f is a bit tricky to design, but maybe something closer to the capital F, and designed narrower, would help keep the overall personality of the other letters and still identify it as a lowercase f instead of capital F? I know that Nathan mentioned a more "hooked" shape on the top of f, but it seems too odd and hard to designed with such a heavy top weight.

Notes with the numbered comments on the PDF: 
[Matemasie_Lisa_feedback_231201.pdf](https://github.com/YADAMSS/Matemasie-Font/files/13527526/Matemasie_Lisa_feedback_231201.pdf)
Capitals:
- [x] G: the middle bar seems too straight. More curves would be more coherent with the typeface style.
- [x] M: have you tried to pull the middle part even lower? 
- [x] Y: top part looks too light compared to the other capitals.
- [x] X: maybe try another construction for X? Something that looks more like a chromosome shape? It could help to have a narrower letter.
- [x] W: the middle looks too heavy, and too vertical.
- [x] Z: its top looks too boxy, and the bottom horizontal seems too straight. I think that what is needed here is just a liiittle more curves to make it more "Matemasie-esque" without loosing the letter.
- [x] P: bottom of P should be related with the bottom of F. In P, it looks more pointy than in F.
- [x] R: the top counter could be slightly smaller, then pull the horizontal connection higher, and have the leg of P more related to that of K + a similar rounded corner as you have in B.
- [x] A, H and N: the thinner parts don't look consistent. And the same issue is to be found in other letters as well. The challenge here would be to identity where are the lightest spots of the letters, and make it consistent on all.

Lowercase:
- [x] e: maybe a loop that goes less low would help to make an e that reads easier?
- [x] f: as commented above.
- [x] g: the bottom of g can be longer.
- [x] l: you can have a smoother weight transition from top to bottom, and end with that curl
- [x] r: narrower r, and top that should look more closer to that of n, m, etc.
- [x] t: that t looks tricky too. But it could be more related to lowercase l, and its top doesn't need to go so far up. Lowercase t usually gets between the ascender and x-height level.
- [x] u: be careful with the weight of both top sides. I believe they should be more similar.
- [x] v: its outer sides looks almost pointy, not curved enough??
- [x] w: as Nathan mentioned, it is too wide. The inner counters can be smaller.
- [x] y: have you tried something more like a lowercase v + a tail (similar to the tail of g) ?
- [ ]. z: same issue as capital Z, like Nathan mentioned.

Letters with diacritics:
- [x] aogonek: the ogonek should look like it grows from the bottom of the letter, and should be darker on its end instead of ending thinner. You can check out this nice book for more info about Central European diacritics: http://theinsectsproject.eu/
Or this thread with great links to info on other diacritics: https://twitter.com/aleksamul/status/1057350288061984770
- [x] the i with diacritics looks like you added a diacritic on top of an i with its dot. It should be a diacritic + an i without dot.
- [x] ae ligature should be designed as one glyph instead of two components combined together, especially with your design of Matemasie.
- [x] Some glyphs (asterisk, numbersign, multiply, plus) look like their shapes have separated elements overlapped on top of each other. Because of the uniqueness of Matemasie, these should be their starting point as they are now, but need more work to adjust their shapes. You can look up for the Poggendorf optical illusion, very neat stuff :)

**Comment by LisaHuang2017** [comment]
Updated feedback based on Matemasie Glyphs file downloaded on Jan. 5, 2024:
There have been quite a lot of progress. But some issues are still around, and some others are linked to what has already been mentioned in other issues that will be linked here.

[Matemasie_fb_Lisa_060123.pdf](https://github.com/YADAMSS/Matemasie-Font/files/13849959/Matemasie_fb_Lisa_060123.pdf)

- [ ] F The middle bar should be lower to have more balance of the counters
- [ ] G Middle bar could be shorter to bring better legibility
- [ ] S and s need better left/right symmetry (This has been mentioned is issue #15 )
- [ ] Y Top part still looks too light, and too narrow, compared to other capitals (mentioned in this same issue above)
- [ ] Thorn Should be wider in order to look more like a capital instead of the lowercase thorn being scaled down
- [ ] Germandbls Looks too boxy and a bit too narrow to look like a capital letter (mentioned in issue #16 )
- [ ] Spacing issues in AE, (think of borrowed spacing values from the original letter or related letter)
- [ ] L Right side spacing needs to be smaller
- [ ] b, d, p, q, r The connection between vertical stem and curves need to be more consistent in shape. In "r" it looks too exaggerated compared to every other related shape
- [ ] e The bottom counter looks too big, you could add more weight to the bottom left curve
- [ ] t The top is too high, it doesn't need to go as high as the ascenders
- [ ] v It looks too much like a "u" because its bottom is too rounded
- [ ] y Be careful with the symmetry of the top part, and the bottom has to be related with that of "g"
- [ ] ae Needs some adjustments on the weight distribution and left/right symmetry 
- [ ] hbar and eng Be careful as the h in hbar and n in eng look like it's another part and the default letter...

About the diacritics on uppercase and lowercase, both:
- [ ] They need to be more center-aligned for several glyphs (Adieresis, Amacron, Atilde, Ydieresis)
- [ ] breve and macron are too wide. Keep in mind that they go in a set, so should be visually consistent in terms of weight, widths, and distance to the letters
- [ ] Ccaron Why is the caron on top of C different from that of the other letters with the same caron?
- [ ] Otilde, Scaron Why are these not combined with a capital?
- [ ] dotlessi and dotlessj should be the same i and j as the default glyph, they just don't have the dot
- [ ] dcaron The commaaccent needs to be closer to the d
- [ ] oslash The stroke needs to be shorter and more slanted
- [ ] rcommaaccent The comma has to be aligned to the bottom of the stem instead of the letter's entire width
- [ ] tcaron The commaaccent is the same as in dcaron

**Comment by YADAMSS** [comment]
<img width="93" alt="Screenshot 2024-01-18 at 15 48 20" src="https://github.com/YADAMSS/Matemasie-Font/assets/47873757/cb58f482-9cb4-4ef7-bf14-33f7e496d6d9">

Hello Lisa, here are idotless and jdotless. I think the dotless are smaller than normal letters.

**Comment by LisaHuang2017** [comment]
> <img alt="Screenshot 2024-01-18 at 15 48 20" width="93" src="https://private-user-images.githubusercontent.com/47873757/297778610-cb58f482-9cb4-4ef7-bf14-33f7e496d6d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTE2MjUsIm5iZiI6MTcwNTU5MTMyNSwicGF0aCI6Ii80Nzg3Mzc1Ny8yOTc3Nzg2MTAtY2I1OGY0ODItOWNiNC00ZWY3LWJmMTQtMzNmN2U0OTZkNmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE1MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NDRiNDQyZDMxMmY5YzI2MGZmNTAxZmU2OTZjNmQwZjNjNzNiMmRhZDU4YTliYjk1NjU3MzI3OWNlYjA1OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.meD4rpNFSmoMa2eigjKiFCH2NPhCEPKgeVeH1OeudWo">
> 
> Hello Lisa, here are idotless and jdotless. I think the dotless are smaller than normal letters.

The idotless and jdotless are i and j without the dot (hence the name). Ideally, the i should even be an idotless as a component, plus a dotaccent also as a component. And same applies for the j.

**Comment by YADAMSS** [comment]
thank you Lisa I got it!
