### ISSUE TITLE
Contour directions

### ISSUE THREAD

**Issue by LisaHuang2017** [YADAMSS/Matemasie-Font#6]
On Matemasie Glyphs file from Dec. 01, 2023:
Some contours are not in the correct direction. Image below:
<img width="638" alt="Capture d’écran 2023-12-01 à 11 04 42" src="https://github.com/YADAMSS/Matemasie-Font/assets/32390132/28ab0f86-e38e-44d7-b2a5-ebe04d0afc73">

These need to be reversed to that (below):
<img width="735" alt="Capture d’écran 2023-12-01 à 11 04 56" src="https://github.com/YADAMSS/Matemasie-Font/assets/32390132/f7e1c944-7995-4a21-b228-2449445bd926">

**Comment by YADAMSS** [comment]
thanks I will check also  for all the letters!
