### ISSUE TITLE
Ideas for f and t

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#7]
So, I thought I might start a separate issue for f and t, since those two letters are somewhat related in construction. Based on @LisaHuang2017 's feedback on #5 , it sounds like I might not have been clear about what I was trying to say previously about f and F looking too similar (in an earlier revision). I think the main issue I wanted to highlight when discussing the f in #3 was that the width and the flat-ness of the top of the f were too close to the width and flatness of the top of F, so that made them a little difficult to tell apart from each other.

What I was thinking for the "hook"ness at the top of f that could keep it distinct as the lowercase letter was to keep it short in length and to keep it round. It certainly doesn't need to loop around a full 180 degrees; I just mean that if the top of f should be read as a curve motion, and not look like it's a separate straight stroke (which is how the top of F is usually done).

![Screenshot from 2023-12-02 12-48-22](https://github.com/YADAMSS/Matemasie-Font/assets/2192132/094edcaa-bbd3-4539-ae5f-a61460ac1f55)

I have a very crude sketch attached here; maybe that will be clearer this time.

On the way that the (current) f and t corners are constructed, they both look a bit awkward, and I think that one reason might be the points. In the screenshots below, there's a comparison between the bottom of lowercase-l and that of lowercase-t.

All I did here was number the points on the contours, starting from the end where there's a single point "A". In the lowercase-l, the two sides of the contour have the "B" points roughly equally apart from each other, and the same with the "C" points. In the lowercase-t, there are more points on the bottom side of the contour, and they don't line up across each other very directly from the ones on the top side. (Obviously I think that this labeling stops where the whole stroke of the letter changes direction, but for just the base of the letter, it's useful hopefully).

If you think about where a paintbrush or something would move to make the shape of the letter, the two sides of the paintbrush always stay roughly across from each other as it moves. So I think the extra points on the bottom of the t contour, and the bottom-of-contour points being too far out of alignment from the top-of-contour points, both make the shape less natural in its curve. 

<img width="328" alt="Screen Shot 2023-12-02 at 12 27 04 PM" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/5c2f0af0-3dcf-4793-a833-78a60ab2df3e">
<img width="357" alt="Screen Shot 2023-12-02 at 12 29 23 PM" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/a202132a-6f48-49f1-b82e-7ea3eeefcd3f">

So perhaps if you reduce the number of bottom-of-contour points there on the t, and try to adjust the shape while keeping pairs of points roughly across from each other, it would be easier to find a shape that looks fluid and natural there.

**Comment by YADAMSS** [comment]
Hi Nate tks, I'll reduce the number of bottom-of-contour points on the t, and  adjust the shape  as you suggested!

Also, I think I'll design alternatives for both "t" and "f" based on Lisa and your's recommendations, and at the end, we'll see how they can be adjusted or which one reflects the spirit of Matemasie better.
