### ISSUE TITLE
Check glyphs for points at extrema

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#8]
Most of the glyphs have a point at the extrema (maximum and minimum, vertical and horizontal) for each contour, but there are some that do not.

It can happen accidentally; the image here is from lowercase-j. The actual vertical minimum is where the arrow is. You can see that the control point arm on the right actually crosses below the purple line; that pulls the location of the minimum downward. So that is a situation to check for; in such situations, adding the extreme then removing the previous/nearby point will result in the contour being easier to manipulate.
<img width="792" alt="Screen Shot 2023-12-02 at 1 35 31 PM" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/f0ea02c9-3402-43a8-8a52-7b0eef7815af">

Certainly it's fine to draw that way as you work, but it's important to regularly check the glyphs and do "Add Extremes", then remove any additional points that are too-close on the contour. So please consider this an issue to make it a regular check to be done.

**Comment by YADAMSS** [comment]
thank you Nate ,I will check  further the problem with point at the extrema,

**Comment by tphinney** [comment]
There are still many glyphs with this problem in the latest source posted. This includes:

J L Lslash M Oslash OE P Q R V X Y Z
a aogonek ae b c
and so on


Glyphs with subtle extrema issues:

aogonek (leftmost point has non-vertical top handle)
C and E (bottom terminal)
S (lower right extreme is slanted a bit)

**Comment by YADAMSS** [comment]
Thanks, I'm checking them out!
