### ISSUE TITLE
Floating symbols

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#9]
This is minor, since I think it can be solved by simple scaling-up, but the copyright, registration, and trademark symbols should be bigger. They are small enough at present that they can be difficult to read.

Quick example: 
<img width="478" alt="Screen Shot 2023-12-16 at 1 55 20 PM" src="https://github.com/YADAMSS/Matemasie-Font/assets/2192132/d6b2fe78-8ee7-4fcd-9e68-1233cb101c44">

I don't think there's a "clear and absolute rule" for what the size of them should be, but typically they would be roughly equal in width to a standard, lowercase letter. Or you might try setting them to be some particular proportion in height, like 50% of the cap height or something. Either way, just put them into a test sequence, step away for a minute or two, then look again and see if you immediately read it or if it takes your eye some time. That's all you need to shoot for: make it so that it's immediately recognizable by a person reading.

On their positions, I think I expected them to be with their tops equal to the tops of the capitals or numbers, but I would not consider that a requirement. Try a few, or see if other designers have suggestions. Getting the size optimized, so that they are recognizable to people as they read, is definitely the more important thing when someone uses those symbols.

**Comment by YADAMSS** [comment]
Hi Nate,
Thank you for this note, I have tried to compare with other fonts, and I noticed that in most cases the copyright and registered have the same height as the caps like O,C,

Also, I increased trademark proportions. What do you think?
![Screenshot 2023-12-18 at 06 00 32](https://github.com/YADAMSS/Matemasie-Font/assets/47873757/1e6418fb-abfe-4ec5-98a4-de6ec0f16530)

**Comment by tphinney** [comment]
Sorry to be late to commenting.

The new copyright symbol is lovely. In most typefaces, it is pretty a full-height character—that is, baseline to numeral height (or cap height, but if they differ, numeral height is a better choice), plus overshoot.

In many professional fonts, the registered symbol is raised, with a top at the ascender height or (usually) higher, and a total height that is that of an x-height character or smaller (perhaps half that of a cap). If it is designed larger, proper typesetting typically calls for it to be set smaller and raised in most situations. So making it that way in the first place is my own preference. That said, I have certainly seen full-height registered symbols—although I believe this is less useful and not best practice.

For the trademark symbol, being raised and smaller like I just described above is even more common, although I will still hesitate to call it universal.

Microsoft’s character design guidelines offer both approaches for registered and trademark, and say copyright should be full-size.

The classic AGFA type design standards manual (never made publicly available) suggest trademark should top-align with the caps or ascender, and show it around half x-height in total vertical size. They say registered can go either way, but do talk about how if it is made full-size that will have to be corrected in typesetting. And they say copyright should be full size.

**Comment by YADAMSS** [comment]
@tphinney Thanks for your comment, I'll take it into consideration!
